# Generated by Django 3.1.4 on 2020-12-08 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=255, verbose_name='Direccion')),
                ('dni', models.CharField(default=None, max_length=255, verbose_name='DNI')),
                ('telephone', models.CharField(default=None, max_length=255, verbose_name='Telefono fijo')),
                ('mobile', models.CharField(default=None, max_length=255, verbose_name='Mobil')),
                ('portrait_img', models.CharField(default=None, max_length=255, verbose_name='Imagen')),
                ('birth_date', models.DateField(default=None, verbose_name='Fecha de nacimiento')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
