# Generated by Django 3.1.4 on 2020-12-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_crud', '0001_initial'),
        ('cv_crud', '0002_auto_20201208_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='portrait_img',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='telephone',
        ),
        migrations.AddField(
            model_name='cv',
            name='candidate',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate_crud.candidate'),
        ),
    ]
